### ISSUE TITLE
Adding font smoothing

### ISSUE THREAD

**Issue by pawelklasa** [hazelcast/frontend-shared#23]
To ensure the best font-weight appearance, lets's use font smoothing. This delivers a truer and more legible interpretation of a font-set across macs and is more consistent with PC display in terms of weight. 

{ -webkit-font-smoothing: antialiased; }

**Comment by danad02** [comment]
Someone with Mac would be a good match for this issue.

**Comment by jankoritak** [comment]
I'll have a look.

**Comment by jankoritak** [comment]
Did a bit of research and from what I understand, changing (meaning disabling sub-pixel rendering in favour of anti-aliasing) is quite a controversial move, unless we're working with dark-mode.

To me, sub-pixel rendering seems (well, it actually is) superior technology over antialiasing and I would avoid turning it off.

Do we absolutely need to do this, @pawelklasa?

**Comment by danad02** [comment]
Not to mention that font smoothing feature is non-standard and is not on a standards track.

**Comment by pawelklasa** [comment]
The only problem is the iPads and iPhones of this world, as they cannot support subpixel rendering, is it something we should use then?

Also, I think we should have a session where we apply antialiasing to H1 H2 H3 body text and compare it with system rendering and see what we get? As opposed to antialiasing.

**Comment by jankoritak** [comment]
The default value for `font-smooth(ing)` is `auto`. With current implementations, the behaviour is following.

- `-webkit-font-smoothing` - Let the browser decide (Uses subpixel anti-aliasing when available; this is the default)
- `-moz-osx-font-smoothing` - Allow the browser to select an optimization for font smoothing, typically grayscale.

The browser is capable of resolving this on it's own, without our assistance. In case subpixel rendering is available, it is applied. In case it is not, the browser opts for anti-aliasing. This is the case for webkit, moz is analogic.

As for mobile devices, subpixel rendering is not supported due to portrait/landscape mode, we cannot do much about this. Mobile devices fall back to anti-aliasing ootb.

**Comment by pawelklasa** [comment]
Sounds good to me!

**Comment by jankoritak** [comment]
We can close this one then.
